FROM nginx

EXPOSE 80

ADD https://raw.githubusercontent.com/maheshbabu22neeli/docker-instruction/refs/heads/main/README.md /tmp

ADD apache-maven-3.6.3-bin.zip /tmp

CMD ["nginx", "-g", "daemon off;"]